version: "3.8"
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PANASONIC_USERNAME
      - PANASONIC_PASSWORD
    volumes:
      - /tmp/config:/config
      - /Users/david/src/panasonic-aircon/custom_components:/config/custom_components
    ports:
      - "8123:8123"
