[project]
name = "panasonic-aircon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = []

[dependency-groups]
dev = [
    "homeassistant>=2023.7.3",
    "httpx>=0.28.1"
]
